<?php

/**
 * @file
 * Contains commerce_order_pdf.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function commerce_order_pdf_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_pdf module.
    case 'help.page.commerce_pdf':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module provides the facility to print the invoice in pdf format.') . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<p>' . t('To use this module you have to install it. Then go to the /commerce/orders. Here you will find a button to print the invoice.') . '</p>';
       
      return $output;

    default:
  }
}
